<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>syllabus</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Syllabus_files/libs/clipboard/clipboard.min.js"></script>
<script src="Syllabus_files/libs/quarto-html/quarto.js"></script>
<script src="Syllabus_files/libs/quarto-html/popper.min.js"></script>
<script src="Syllabus_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Syllabus_files/libs/quarto-html/anchor.min.js"></script>
<link href="Syllabus_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Syllabus_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Syllabus_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Syllabus_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Syllabus_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">



<section id="fondamenti-di-economia-comportamentale---syllabus" class="level1">
<h1>Fondamenti di Economia Comportamentale - <em>Syllabus</em></h1>
<section id="docenti" class="level2">
<h2 class="anchored" data-anchor-id="docenti">📌 Docenti</h2>
<p><a href="https://sites.google.com/view/matildegiaccherini">Matilde Giaccherini</a> (Modulo 1)<br>
Email: mgiaccherini <em>chiocciola</em> luiss <em>punto</em> it<br>
Ricevimento: su appuntamento</p>
<p><a href="https://ncampigotto.github.io">Nicola Campigotto</a> (Modulo 2)<br>
Email: ncampigotto <em>chiocciola</em> luiss <em>punto</em> it<br>
Ricevimento: su appuntamento</p>
</section>
<section id="assistenti-alla-didattica" class="level2">
<h2 class="anchored" data-anchor-id="assistenti-alla-didattica">📌 Assistenti alla didattica</h2>
<p>Maria Paola Pagliarulo (Canale A)<br>
Email:<br>
Ricevimento: su appuntamento</p>
<p>Emma Manneschi (Canale B)<br>
Email:<br>
Ricevimento: su appuntamento</p>
</section>
<section id="pagine-del-corso" class="level2">
<h2 class="anchored" data-anchor-id="pagine-del-corso">📌 Pagine del corso</h2>
<p>Per eseguire l’accesso sono necessarie le credenziali LUISS.</p>
<ul>
<li>Canale A: <a href="https://learn.luiss.it/course/view.php?id=23313" class="uri">https://learn.luiss.it/course/view.php?id=23313</a></li>
<li>Canale B: <a href="https://learn.luiss.it/course/view.php?id=23314" class="uri">https://learn.luiss.it/course/view.php?id=23314</a></li>
</ul>
</section>
<section id="orario-delle-lezioni" class="level2">
<h2 class="anchored" data-anchor-id="orario-delle-lezioni">📌 Orario delle lezioni</h2>
<p>Tutte le lezioni si tengono nella sede di viale Romania. Le lezioni del lunedì (Canale A) e del giovedì (Canale B) sono erogate in plenaria o in due gruppi distinti a settimane alterne. Per ulteriori dettagli e informazioni riguardanti eventuali variazioni d’orario, consultare l’<a href="https://pianificazionespazi.luiss.it/PortaleStudentiLuiss">agenda web</a> di ateneo.</p>
<ul>
<li>Canale A
<ul>
<li>Lunedì, 11.30-13.00 (aula A307)<br>
<ins>oppure</ins> Lunedì, 11.30-13.00 (gruppo 1, aula A307) e 14.00-15.30 (gruppo 2, aula A104)<br>
</li>
<li>Venerdì, 13.45-15.15 (aula A204)<br>
</li>
</ul></li>
<li>Canale B
<ul>
<li>Lunedì, 17.15-18.45 (aula A209)<br>
</li>
<li>Giovedì, 14.45-16.15 (aula A204)<br>
<ins>oppure</ins> Giovedì, 14.45-16.15 (gruppo 1, aula A204) e 16.30-18.00 (gruppo 2, aula A307)</li>
</ul></li>
</ul>
<blockquote class="blockquote">
<p>[!IMPORTANT] La frequenza è obbligatoria ed è oggetto di valutazione. Le lezioni non vengono registrate.</p>
</blockquote>
</section>
<section id="prerequisiti" class="level2">
<h2 class="anchored" data-anchor-id="prerequisiti">📌 Prerequisiti</h2>
<p>Elementi di microeconomia e statistica.</p>
</section>
<section id="panoramica-del-corso" class="level2">
<h2 class="anchored" data-anchor-id="panoramica-del-corso">📌 Panoramica del corso</h2>
<p>Questo corso funge da introduzione all’<a href="https://news.uchicago.edu/explainer/what-is-behavioral-economics">economia comportamentale</a>. L’obiettivo è quello di fornire una solida comprensione di: - quali sono i fattori psicologici che influenzano i processi decisionali; - come è possibile far leva su questi fattori per implementare strategie aziendali e politiche pubbliche riguardanti la salute, l’energia, la tassazione e altro ancora.</p>
<p>Il corso si compone di due moduli. Il modulo 1 introduce le basi concettuali dell’economia comportamentale e le contrappone alla teoria microeconomica tradizionale. Gli argomenti trattati in questo modulo includono la teoria del prospetto, la <em>loss aversion</em> e altre euristiche e <em>bias</em> che influenzano le decisioni. Il modulo 2 tratta argomenti quali l’elaborazione di nuove informazioni, i pregiudizi, l’altruismo, le interazioni strategiche e i <em>nudge</em>.</p>
<p>In fondo a questa pagina è riportato il programma dettagliato del corso. Le lezioni combinano teoria ed evidenza empirica.</p>
</section>
<section id="manuale" class="level2">
<h2 class="anchored" data-anchor-id="manuale">📌 Manuale</h2>
<p>Edward Cartwright (2018), <a href="https://www.routledge.com/Behavioral-Economics/Cartwright/p/book/9781138097124"><em>Behavioral Economics</em></a>, terza edizione, Routledge</p>
</section>
<section id="modalità-di-valutazione" class="level2">
<h2 class="anchored" data-anchor-id="modalità-di-valutazione">📌 Modalità di valutazione</h2>
<p>Per informazioni sul regolamento di ateneo in materia di esami, consultare l’appossito <a href="https://github.com/ncampigotto/FECOMP_LUISS_2024/blob/main/Altro/Luiss_FEB_Handbook_7030_ITA.pdf">vademecum</a>.</p>
<section id="studenti-frequentanti" class="level3">
<h3 class="anchored" data-anchor-id="studenti-frequentanti">▶️ Studenti frequentanti</h3>
<table class="table">
<colgroup>
<col style="width: 55%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Prova</th>
<th style="text-align: left;">Punteggio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Presenza e partecipazione in classe</td>
<td style="text-align: left;">Fino a 3 punti</td>
</tr>
<tr class="even">
<td style="text-align: left;">Quiz in classe (x5)</td>
<td style="text-align: left;">Fino a 5 punti (fino a un punto per quiz)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Elaborati di analisi di dati sperimentali (x3)</td>
<td style="text-align: left;">Fino a 9 punti (fino a 3 punti per elaborato)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><em>Policy brief</em></td>
<td style="text-align: left;">Fino a 5 punti</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Esame finale</td>
<td style="text-align: left;">Fino a 10 punti</td>
</tr>
</tbody>
</table>
<p>La stesura degli elaborati di analisi dei dati e del <em>policy brief</em> avviene in gruppi, la cui composizione è comunicata all’inizio del corso. Il voto finale è assegnato in trentesimi e la lode viene assegnata solo qualora il punteggio complessivo superi il 30.</p>
<blockquote class="blockquote">
<p>[!IMPORTANT] Attenzione alle seguenti regole: 1. Chi non partecipa a un quiz in classe riceve zero punti per quel quiz. 2. Gli elaborati di gruppo devono essere consegnati entro la data di scadenza prevista. Elaborati non consegnati o consegnati in ritardo sono valutati con zero punti. Non sono accettate scuse per le consegne tardive. 3. Il punteggio relativo a frequenza e partecipazione è assegnato come segue: 2 punti per chi partecipa a oltre l’80% delle lezioni; 1 punto per chi partecipa a una percentuale di lezioni compresa tra il 50% e l’80%; 0 punti per chi partecipa a meno del 50% delle lezioni. Il terzo punto è assegnato dai docenti sulla base della partecipazione in classe.</p>
</blockquote>
</section>
<section id="studenti-non-frequentanti" class="level3">
<h3 class="anchored" data-anchor-id="studenti-non-frequentanti">▶️ Studenti non frequentanti</h3>
<table class="table">
<colgroup>
<col style="width: 55%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Prova</th>
<th style="text-align: left;">Punteggio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Esame finale</td>
<td style="text-align: left;">Fino a 32 punti</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="struttura-degli-esami" class="level2">
<h2 class="anchored" data-anchor-id="struttura-degli-esami">📌 Struttura degli esami</h2>
<ul>
<li><p>L’esame finale per gli studenti <ins>frequentanti</ins> consiste di una sola domanda a risposta aperta tratta dal programma del Modulo 1 o del Modulo 2.</p></li>
<li><p>L’esame finale per gli studenti <ins>non frequentanti</ins> consiste di tre domande a risposta aperta tratte da entrambi i moduli. Due domande sono basate sul manuale, mentre la terza domanda è basata sulle altre letture obbligatorie.</p></li>
</ul>
<p>Durante gli esami non è possibile consultare manuale e appunti.</p>
</section>
<section id="quiz-in-classe" class="level2">
<h2 class="anchored" data-anchor-id="quiz-in-classe">📌 Quiz in classe</h2>
<p>Il corso prevede 5 quiz in itinere svolti in classe, ciascuno della durata di 20 minuti circa. I quiz valutano la comprensione di uno o due articoli scientifici da leggere prima della lezione.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Numero quiz</th>
<th style="text-align: left;"><strong>Articolo</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Kahneman, Knetsch e Thaler (1991), “<a href="https://doi.org/10.1257/jep.5.1.193">Anomalies: The endowment effect, loss aversion, and status quo bias</a>”, <em>Journal of Economic Perspectives</em>, vol.&nbsp;5, n.&nbsp;1, pp.&nbsp;193-206</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Andreoni, Kuhn, List, Samek, Sokal e Sprenger (2019), “<a href="https://doi.org/10.1016/j.jpubeco.2019.06.007">Toward an understanding of the development of time preferences: Evidence from field experiments</a>”, <em>Journal of Public Economics</em>, vol.&nbsp;177, n.&nbsp;104039</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Balafoutas, Nikiforakis e Rockenbach (2014), “<a href="https://doi.org/10.1073/pnas.1413170111">Direct and indirect punishment among strangers in the field</a>”, <em>Proceedings of the National Academy of Sciences</em>, vol.&nbsp;111, n.&nbsp;45, pp.&nbsp;15924-15927</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Gneezy e Rustichini (2000), “<a href="https://doi.org/10.1162/003355300554917">Pay enough or don’t pay at all</a>”, <em>Quarterly Journal of Economics</em>, vol.&nbsp;115, n.&nbsp;3, pp.&nbsp;791-810</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Meyer e Tripodi (2021), “<a href="https://doi.org/10.1016/j.joep.2021.102434">Image concerns in pledges to give blood: Evidence from a field experiment</a>”, <em>Journal of Economic Psychology</em>, vol.&nbsp;87, n.&nbsp;102434</td>
</tr>
<tr class="even">
<td style="text-align: left;">5</td>
<td style="text-align: left;">Blumenstock, Callen e Ghani (2018), “<a href="https://doi.org/10.1257/aer.20171676">Why do defaults affect behavior? Experimental evidence from Afghanistan</a>”, <em>American Economic Review</em>, vol.&nbsp;108, n.&nbsp;10, pp.&nbsp;2868-2901</td>
</tr>
</tbody>
</table>
<p>I quiz sono svolti in autonomia. Ogni quiz consiste di 5 domande a scelta multipla o vero/falso. Non sono previste penalità per le risposte sbagliate e ogni risposta corretta vale 0,2 punti (quindi il punteggio massimo è di 1 punto per quiz). Agli studenti assenti sono assegnati zero punti.</p>
<p>Il punteggio totale è dato dalla somma dei punteggi di tutti e cinque i quiz, arrotondata al numero intero più vicino.</p>
<blockquote class="blockquote">
<p>[!IMPORTANT] Le letture riportate nella tabella qui sopra sono <ins>obbligatorie</ins> anche per gli studenti <ins>non frequentanti</ins> e sono oggetto di una delle tre domande dell’esame.</p>
</blockquote>
</section>
<section id="elaborati-di-analisi-dei-dati" class="level2">
<h2 class="anchored" data-anchor-id="elaborati-di-analisi-dei-dati">📌 Elaborati di analisi dei dati</h2>
<p>Parte delle lezioni prevede la partecipazione a degli esperimenti. Ciascun gruppo ha poi il compito di analizzare i dati sperimentali e redigere tre brevi elaborati per rispondere a una serie di domande.</p>
<p>L’analisi dei dati è effettuata utilizzando <a href="https://www.stata.com">Stata</a>. L’Università fornisce una licenza gratuita di Stata a tutti gli studenti. È responsabilità degli studenti assicurarsi che il software sia correttamente installato sul proprio computer.</p>
</section>
<section id="policy-brief" class="level2">
<h2 class="anchored" data-anchor-id="policy-brief">📌 <em>Policy brief</em></h2>
<p>Un <em>policy brief</em> è un documento che sintetizza i risultati e le implicazioni di una o più ricerche scientifiche per i decisori politici. Traducendo il linguaggio tecnico in termini comprensibili, rende accessibile l’evidenza empirica in modo da informare e guidare le politiche pubbliche. Per un esempio, cliccare <a href="https://github.com/ncampigotto/FECOMP_LUISS_2024/blob/main/Altro/PolicyBrief_Impact_Study_Vivamos_Mejor.pdf">QUI</a>.</p>
<p>All’inizio del corso, ciascun gruppo deve scegliere uno degli articoli proposti nella tabella qui sotto, coordinandosi con gli altri gruppi in modo tale che nessun articolo venga scelto da più di tre gruppi. Le scelte vanno riportate <a href="https://docs.google.com/spreadsheets/d/1nXle0We9WTz8DmncqyGHKRNjiqqXuXZ9uBjFY-FqQ_o/edit?usp=sharing">QUI</a>.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;"><strong>Articolo</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Alatas, Chandrasekhar, Mobius e Paladines (2024), “<a href="https://doi.org/10.1093/ej/uead102">Do celebrity endorsements matter? A Twitter experiment promoting vaccination in Indonesia</a>”, <em>Economic Journal</em>, vol.&nbsp;134, n.&nbsp;659, pp.&nbsp;913-933</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Burland, Dynarski, Michelmore, Owen e Raghuraman (2023), “<a href="https://doi.org/10.1257/aeri.20220094">The power of certainty: Experimental evidence on the effective design of free tuition programs</a>”, <em>American Economic Review: Insights</em>, vol.&nbsp;5, no. 3, pp.&nbsp;293-310</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Coffman, Featherstone e Kessler (2017), “<a href="https://doi.org/10.1257/app.20140468">Can social information affect what job you choose and keep?</a>”, <em>American Economic Journal: Applied Economics</em>, vol.&nbsp;9, n.&nbsp;1, pp.&nbsp;96-117</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Giné, Karlan e Zinman (2010), “<a href="https://doi.org/10.1257/app.2.4.213">Put your money where your butt is: A commitment contract for smoking cessation</a>”, <em>American Economic Journal: Applied Economics</em>, vol.&nbsp;2, n.&nbsp;4, pp.&nbsp;213-235</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">Homonoff (2018), “<a href="https://doi.org/10.1257/pol.20150261">Can small incentives have large effects? The impact of taxes versus bonuses on disposable bag use</a>”, <em>American Economic Journal: Economic Policy</em>, vol.&nbsp;10, n.&nbsp;4, pp.&nbsp;177-210</td>
</tr>
</tbody>
</table>
<p>Alcuni articoli discutono più di un risultato: la scelta di quanti e quali risultati riportare nel <em>policy brief</em> è a discrezione del gruppo. L’elaborato è valutato anche sulla base della capacità di identificare e descrivere accuratamente i risultati più importanti.</p>
<p>Il documento non deve superare le 3 pagine di lunghezza e può contenere tabelle e grafici presi dall’articolo o creati <em>ex novo</em> dal gruppo. Il testo va organizzato utilizzando le seguenti sezioni. - Obiettivo dell’intervento di policy (2-3 frasi). - <em>Background</em>: perché l’intervento ci interessa? Qual è il contesto in cui è stato implementato? Quali euristiche o <em>bias</em> vengono considerati? - Metodi: in cosa consiste l’intervento? Qual è il campione considerato? - Risultati: descrizione dei principali risultati dell’intervento. - Raccomandazioni di policy: qual è la rilevanza dello studio per il disegno di nuove politiche pubbliche?</p>
<blockquote class="blockquote">
<p>[!IMPORTANT] - Gli elaborati vanno caricati sulla pagina del corso entro e non oltre le <ins>23.59 di venerdì 22 novembre 2024</ins>. - Il contenuto degli articoli riportati nella tabella qui sopra <ins>non</ins> è oggetto di valutazione nell’esame finale.</p>
</blockquote>
</section>
<section id="programma-dettagliato" class="level2">
<h2 class="anchored" data-anchor-id="programma-dettagliato">📌 Programma dettagliato</h2>
<p>Eventuali modifiche a questo programma sono comunicate durante il corso, così come la data e l’ora esatte degli esperimenti e dei quiz in classe.</p>
<blockquote class="blockquote">
<p>[!IMPORTANT] I capitoli del manuale elencati qui sotto sono oggetto di due delle tre domande dell’esame per <ins>non frequentanti</ins>.</p>
</blockquote>
<section id="modulo-1-giaccherini" class="level3">
<h3 class="anchored" data-anchor-id="modulo-1-giaccherini">Modulo 1 (Giaccherini)</h3>
<ul>
<li><code>[Settimana 1]</code> Introduzione all’economia comportamentale
<ul>
<li><em>Letture:</em>
<ul>
<li>Cartwright, Capitolo 1</li>
</ul></li>
</ul></li>
<li><code>[Settimana 2]</code> Euristiche e <em>bias</em>
<ul>
<li><em>Letture:</em>
<ul>
<li>Cartwright, Capitolo 2</li>
<li>Thaler e Sunstein (2008), <em>Nudge: Improving Decisions About Health, Wealth, and Happiness</em>, Yale University Press, Capitolo 1</li>
</ul></li>
<li><em>Attività:</em>
<ul>
<li>❓ Primo quiz in classe<br>
</li>
</ul></li>
</ul></li>
<li><code>[Settimana 3]</code> Introduzione all’analisi dei dati con Stata (porta il tuo laptop!)<br>
</li>
<li><code>[Settimane 4 e 5]</code> Scelte in condizioni di rischio e incertezza
<ul>
<li><em>Letture:</em>
<ul>
<li>Cartwright, Capitolo 3</li>
<li>Levitt, List, Neckermann e Sadoff (2016), “<a href="https://doi.org/10.1257/pol.20130358">The behavioralist goes to school: Leveraging behavioral economics to improve educational performance</a>”, <em>American Economic Journal: Economic Policy</em>, vol.&nbsp;8, n.&nbsp;4, pp.&nbsp;183-2019</li>
<li>Cordes, Dertwinkel-Kalt e Werner (2023), “<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4349674">What drives demand for loot boxes? An experimental study</a>”, working paper</li>
<li>Kirchler, Lindner e Weitzel (2018), “<a href="https://doi.org/10.1111/jofi.12701">Rankings and risk-taking in the finance industry</a>”, <em>Journal of Finance</em>, vol.&nbsp;73, n.&nbsp;5, pp.&nbsp;2271-2302</li>
</ul></li>
<li><em>Attività:</em>
<ul>
<li>🔬 Primo esperimento in classe<br>
</li>
</ul></li>
</ul></li>
<li><code>[Settimana 6]</code> Scelte intertemporali
<ul>
<li><em>Letture:</em>
<ul>
<li>Cartwright, Capitolo 4</li>
<li>DellaVigna e Malmendier (2006), “<a href="https://doi.org/10.1257/aer.96.3.694">Paying not to go to the gym</a>”, <em>American Economic Review</em>, vol.&nbsp;96, n.&nbsp;3, pp.&nbsp;694-719</li>
<li>Levitt, List, Neckermann e Sadoff (2016), “<a href="https://doi.org/10.1257/pol.20130358">The behavioralist goes to school: Leveraging behavioral economics to improve educational performance</a>”, <em>American Economic Journal: Economic Policy</em>, vol.&nbsp;8, n.&nbsp;4, pp.&nbsp;183-2019</li>
</ul></li>
<li><em>Attività:</em>
<ul>
<li>❓ Secondo quiz in classe<br>
</li>
<li>📝 Consegna del primo elaborato sperimentale</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="modulo-2-campigotto" class="level3">
<h3 class="anchored" data-anchor-id="modulo-2-campigotto">Modulo 2 (Campigotto)</h3>
<ul>
<li><code>[Settimane 7 e 8]</code> Apprendimento, narrazioni, pregiudizi e persuasione
<ul>
<li><em>Letture:</em>
<ul>
<li>Cartwright, Capitolo 5 (Sezioni 5.1.0, 5.2.0, 5.2.1 e 5.2.3)</li>
<li>Bursztyn, Rao, Roth e Yanagizawa-Drott (2023), “<a href="https://doi.org/10.1093/restud/rdac065">Opinions as facts</a>”, <em>Review of Economic Studies</em>, vol.&nbsp;90, n.&nbsp;4, pp.&nbsp;1832-1864</li>
<li>Graeber, Roth e Zimmermann (2024), “<a href="https://raw.githubusercontent.com/cproth/papers/master/SSM_May2024.pdf">Stories, statistics, and memory</a>”, <em>Quarterly Journal of Economics</em>, di prossima pubblicazione</li>
<li>Leib, Köbis, Rilke, Hagens e Irlenbusch (2024), “<a href="https://doi.org/10.1093/ej/uead056">Corrupted by algorithms? How AI-generated and human-written advice shape (dis)honesty</a>”, <em>Economic Journal</em>, vol.&nbsp;134, n.&nbsp;658, pp.&nbsp;766-784</li>
<li>Levy (2021), “<a href="https://doi.org/10.1257/aer.20191777">Social media, news consumption, and polarization: Evidence from a field experiment</a>”, <em>American Economic Review</em>, vol.&nbsp;111, n.&nbsp;3, pp.&nbsp;831-870</li>
<li>Mislavsky e Gaertig (2022), “<a href="https://doi.org/10.1287/mnsc.2020.3902">Combining probability forecasts: 60% and 60% is 60%, but likely and likely is very likely</a>”, <em>Management Science</em>, vol.&nbsp;68, n.&nbsp;1, pp.&nbsp;541-563</li>
<li>Schwardmann, Tripodi e van der Weele (2022), “<a href="https://doi.org/10.1257/aer.20200372">Self-persuasion: Evidence from field experiments at international debating competitions</a>”, <em>American Economic Review</em>, vol.&nbsp;112, n.&nbsp;4, pp.&nbsp;1118-1146</li>
</ul></li>
<li><em>Attività:</em>
<ul>
<li>🔬 Secondo esperimento in classe<br>
</li>
</ul></li>
</ul></li>
<li><code>[Settimana 9]</code> Interazioni sociali
<ul>
<li><em>Letture:</em>
<ul>
<li>Cartwright, Capitolo 7 (Sezioni da 7.1.0 a 7.1.5) e 11 (Sezione 11.1.1)</li>
<li>Ehret, Constantino, Weber, Efferson e Vogt (2022), “<a href="https://doi.org/10.1038/s41562-022-01440-5">Group identities can undermine social tipping after intervention</a>”, <em>Nature Human Behavior</em>, vol.&nbsp;6, pp.&nbsp;1669-1679</li>
<li>Fehr e Leibbrandt (2011), “<a href="https://doi.org/10.1016/j.jpubeco.2011.05.013">A field study on cooperativeness and impatience in the tragedy of the commons</a>”, <em>Journal of Public Economics</em>, vol.&nbsp;95, n.&nbsp;9-10, pp.&nbsp;1144-1155</li>
<li>Hermann, Thöni e Gächter (2008), “<a href="https://doi.org/10.1126/science.1153808">Antisocial punishment across societies</a>”, <em>Science</em>, vol.&nbsp;319, n.&nbsp;5868, pp.&nbsp;1362-1367</li>
<li>Levitt e List (2007), “<a href="https://doi.org/10.1257/jep.21.2.153">What do laboratory experiments measuring social preferences reveal about the real world?</a>”, <em>Journal of Economic Perspectives</em>, vol.&nbsp;21, n.&nbsp;2, pp.&nbsp;153-174</li>
</ul></li>
<li><em>Attività:</em>
<ul>
<li>❓ Terzo quiz in classe</li>
<li>🔬 Terzo esperimento in classe<br>
</li>
<li>📝 Consegna del secondo elaborato sperimentale</li>
</ul></li>
</ul></li>
<li><code>[Settimane 10 e 11]</code> Preferenze e confronti sociali
<ul>
<li><em>Letture:</em>
<ul>
<li>Cartwright, Capitolo 7 (Sezioni da 7.2.0 a 7.5.3)</li>
<li>Allcott (2011), “<a href="https://doi.org/10.1016/j.jpubeco.2011.03.003">Social norms and energy conservation</a>”, <em>Journal of Public Economics</em>, vol.&nbsp;95, n.&nbsp;9-10, pp.&nbsp;1082-1095</li>
<li>Andreoni (1990), “<a href="https://doi.org/10.2307/2234133">Impure altruism and donations to public goods: A theory of warm-glow giving</a>”, <em>Economic Journal</em>, vol.&nbsp;100, n.&nbsp;101, pp.&nbsp;464-477</li>
<li>Andreoni, Rao e Trachtman (2017), “<a href="https://doi.org/10.1086/691703">Avoiding the ask: A field experiment on altruism, empathy, and charitable giving</a>”, <em>Journal of Political Economy</em>, vol.&nbsp;125, n.&nbsp;3, pp.&nbsp;625-653</li>
<li>Birkeland, Cappelen, Sørensen e Tungodden (2014), “<a href="https://doi.org/10.1007/s10683-013-9380-x">An experimental study of prosocial motivation among criminals</a>”, <em>Experimental Economics</em>, vol.&nbsp;17, pp.&nbsp;501-511</li>
<li>Cappelen, Eichele, Hugdahl, Specht, Sørensen e Tungodden (2014), “<a href="https://doi.org/10.1073/pnas.1414602111">Equity theory and fair inequality: A neuroeconomic study</a>”, <em>Proceedings of the National Academy of Sciences</em>, vol.&nbsp;111, n.&nbsp;43, pp.&nbsp;15368-15372</li>
<li>DellaVigna, List e Malmendier (2012), “<a href="https://doi.org/10.1093/qje/qjr050">Testing for altruism and social pressure in charitable giving</a>”, <em>Quarterly Journal of Economics</em>, vol.&nbsp;127, n.&nbsp;1, pp.&nbsp;1-56</li>
<li>Fabbri e Bigoni (2021), “<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4114305">How property shapes distributional preferences</a>”, IZA discussion paper, n.&nbsp;14768</li>
<li>Goldstein, Cialdini e Griskevicius (2008), “<a href="https://doi.org/10.1086/586910">A room with a viewpoint: Using norm-based appeals to motivate conservation behaviors in a hotel setting</a>”, <em>Journal of Consumer Research</em>, vol.&nbsp;35, n.&nbsp;3, pp.&nbsp;472-482</li>
<li>Gneezy e Rustichini (2000), “<a href="https://doi.org/10.1086/468061">A fine is a price</a>”, <em>Journal of Legal Studies</em>, vol.&nbsp;29, n.&nbsp;1, pp.&nbsp;1-17</li>
<li>Goette e Tripodi (2024), “<a href="https://doi.org/10.1016/j.jpubeco.2024.105069">The limits of social recognition: Experimental evidence from blood donors</a>”, <em>Journal of Public Economics</em>, vol.&nbsp;231, n.&nbsp;105069</li>
</ul></li>
<li><em>Attività:</em>
<ul>
<li>❓ Quarto quiz in classe</li>
<li>🔬 Quarto esperimento in classe</li>
<li>📝 Consegna del <em>policy brief</em></li>
</ul></li>
</ul></li>
<li><code>[Settimana 12]</code> Salienza e <em>nudge</em>
<ul>
<li><em>Letture:</em>
<ul>
<li>Cartwright, Capitolo 11 (Sezioni da 11.2.0 a 11.2.5)</li>
<li>Chetty, Looney e Kroft (2009), “<a href="https://doi.org/10.1257/aer.99.4.1145">Salience and taxation: Theory and evidence</a>”, <em>American Economic Review</em>, vol.&nbsp;99, n.&nbsp;4, pp.&nbsp;1145-1177</li>
<li>Hagmann, Ho e Loewenstein (2019), “<a href="https://doi.org/10.1038/s41558-019-0474-0">Nudging out support for a carbon tax</a>”, <em>Nature Climate Change</em>, vol.&nbsp;9, pp.&nbsp;484-489</li>
<li>Kurz (2018), “<a href="https://doi.org/10.1016/j.jeem.2018.06.005">Nudging to reduce meat consumption: Immediate and persistent effects of an intervention at a university restaurant</a>”, <em>Journal of Environmental Economics and Management</em>, vol.&nbsp;90, pp.&nbsp;317-341</li>
<li>Madrian e Shea (2001), “<a href="https://doi.org/10.1162/003355301753265543">The power of suggestion: Inertia in 401(k) participation and savings behavior</a>”, <em>Quarterly Journal of Economics</em>, vol.&nbsp;116, n.&nbsp;4, pp.&nbsp;1149-1187</li>
<li>Scheiber (2017) “<a href="https://www.nytimes.com/interactive/2017/04/02/technology/uber-drivers-psychological-tricks.html">How Uber uses psychological tricks to push its drivers’ buttons</a>, <em>New York Times</em></li>
</ul></li>
<li><em>Attività:</em>
<ul>
<li>❓ Quinto quiz in classe</li>
<li>📝 Consegna del terzo elaborato sperimentale</li>
</ul></li>
</ul></li>
</ul>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>